use_frameworks!
platform :ios, '10.0'

target 'HLYNetworking_Example' do
  pod 'HLYNetworking', :path => '../'

  target 'HLYNetworking_Tests' do
    inherit! :search_paths

    pod 'Alamofire'
  end
end
